default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  host: localhost
  database: dices_development
test:
  <<: *default
  database: dices_test
production:
  <<: *default
  database: dices_production
